/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.GUI;

import com.example.GUI.gestionTrajet.GestionTrajetFrame;
import com.example.GUI.GestionReduction.GestionReductionFrame;
import javax.swing.JFrame;

/**
 *
 * @author yassi
 */
public class AdministrateurFrame extends javax.swing.JFrame {

    /**
     * Creates new form administrateurFrame
     */
    public AdministrateurFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        gestionTrajetButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        gestionCartesReductionButton = new javax.swing.JButton();
        genererRapportButton = new javax.swing.JButton();
        genererRapportButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("ONCF");

        gestionTrajetButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gestionTrajetButton.setText("Gestion des trajets");
        gestionTrajetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionTrajetButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel2.setText("Admin");

        gestionCartesReductionButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gestionCartesReductionButton.setText("Gestion des cartes de réductions");
        gestionCartesReductionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionCartesReductionButtonActionPerformed(evt);
            }
        });

        genererRapportButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genererRapportButton.setText("Rapport Trajets");
        genererRapportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genererRapportButtonActionPerformed(evt);
            }
        });

        genererRapportButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genererRapportButton1.setText("Rapport Voyageurs");
        genererRapportButton1.setActionCommand("Rapport voyageur");
        genererRapportButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genererRapportButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 548, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gestionCartesReductionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gestionTrajetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genererRapportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genererRapportButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gestionTrajetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gestionCartesReductionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(genererRapportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(genererRapportButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionTrajetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionTrajetButtonActionPerformed
        // TODO add your handling code here:
        GestionTrajetFrame gestionTrajet = new GestionTrajetFrame();

        gestionTrajet.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        gestionTrajet.setVisible(true);
    }//GEN-LAST:event_gestionTrajetButtonActionPerformed

    private void gestionCartesReductionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionCartesReductionButtonActionPerformed
        // TODO add your handling code here:
        GestionReductionFrame gestionCarteReduction = new GestionReductionFrame();

        gestionCarteReduction.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        gestionCarteReduction.setVisible(true);
    }//GEN-LAST:event_gestionCartesReductionButtonActionPerformed

    private void genererRapportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genererRapportButtonActionPerformed
        // TODO add your handling code here:
        RapportTrajetFrame rapportFrame = new RapportTrajetFrame();

        rapportFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        rapportFrame.setVisible(true);
    }//GEN-LAST:event_genererRapportButtonActionPerformed

    private void genererRapportButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genererRapportButton1ActionPerformed
        // TODO add your handling code here:
        RapportVoyageurFrame rapportFrame = new RapportVoyageurFrame();

        rapportFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        rapportFrame.setVisible(true);
    }//GEN-LAST:event_genererRapportButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrateurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrateurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrateurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrateurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrateurFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton genererRapportButton;
    private javax.swing.JButton genererRapportButton1;
    private javax.swing.JButton gestionCartesReductionButton;
    private javax.swing.JButton gestionTrajetButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
