/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.GUI;

import com.example.dao.RapportUtil;
import com.example.dao.VoyageurUtil;
import com.example.model.Trajet;
import com.example.model.Voyageur;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yassi
 */
public class RapportVoyageurFrame extends javax.swing.JFrame {

    /**
     * Creates new form RapportVoyageurFrame
     */
    public RapportVoyageurFrame() {
        initComponents();
        
        tablemodele = (DefaultTableModel) tabletrajets.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        allButton = new javax.swing.JButton();
        chercherButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabletrajets = new javax.swing.JTable();
        cIDv = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("ID Voyageur :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("ONCF");

        allButton.setText("Tout afficher");
        allButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allButtonActionPerformed(evt);
            }
        });

        chercherButton.setText("Chercher");
        chercherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chercherButtonActionPerformed(evt);
            }
        });

        tabletrajets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "nom", "prenom", "email", "id réduction", "Tarif"
            }
        ));
        tabletrajets.setShowGrid(true);
        jScrollPane2.setViewportView(tabletrajets);

        cIDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cIDvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cIDv, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(chercherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(allButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chercherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cIDv, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allButtonActionPerformed
        try {
            // TODO add your handling code here:
            ShowALL();
        } catch (SQLException ex) {
            Logger.getLogger(RapportTrajetFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_allButtonActionPerformed

    private void chercherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chercherButtonActionPerformed
        // TODO add your handling code here:
        tablemodele.setRowCount(0);
        try {
            ChercherParID();
        } catch (SQLException ex) {
            Logger.getLogger(RapportTrajetFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_chercherButtonActionPerformed

    private void cIDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cIDvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cIDvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RapportVoyageurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RapportVoyageurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RapportVoyageurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RapportVoyageurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RapportVoyageurFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allButton;
    private javax.swing.JTextField cID;
    private javax.swing.JTextField cIDv;
    private javax.swing.JButton chercherButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabletrajets;
    // End of variables declaration//GEN-END:variables
    private void ChercherParID() throws SQLException {
        VoyageurUtil vu = new VoyageurUtil();
        LinkedList<Voyageur> trajets = new LinkedList<>();
        trajets = vu.rechercherParID(Integer.parseInt(cIDv.getText()));
        DefaultTableModel tablemodeleModele = new DefaultTableModel();
        String[][] tableTrajets;
        tablemodeleModele = (DefaultTableModel) tabletrajets.getModel();
        tableTrajets = new String[trajets.size()][5];

        for (int i = 0; i < trajets.size(); i++) {
            tableTrajets[i][0] = Integer.toString(trajets.get(i).getId());
            tableTrajets[i][1] = trajets.get(i).getNom();
            tableTrajets[i][2] = trajets.get(i).getPrenom();
            tableTrajets[i][3] = trajets.get(i).getEmail();
            tableTrajets[i][4] = Integer.toString(trajets.get(i).getIdReduction());


            tablemodeleModele.addRow(tableTrajets[i]);
        }
    }
    private void ShowALL() throws SQLException {
        VoyageurUtil vu = new VoyageurUtil();
        LinkedList<Voyageur> trajets = new LinkedList<>();
        trajets = vu.showAll();
        DefaultTableModel tablemodeleModele = new DefaultTableModel();
        String[][] tableTrajets;
        tablemodeleModele = (DefaultTableModel) tabletrajets.getModel();
        tableTrajets = new String[trajets.size()][5];

        for (int i = 0; i < trajets.size(); i++) {
            tableTrajets[i][0] = Integer.toString(trajets.get(i).getId());
            tableTrajets[i][1] = trajets.get(i).getNom();
            tableTrajets[i][2] = trajets.get(i).getPrenom();
            tableTrajets[i][3] = trajets.get(i).getEmail();
            tableTrajets[i][4] = Integer.toString(trajets.get(i).getIdReduction());


            tablemodeleModele.addRow(tableTrajets[i]);
        }
    }
    DefaultTableModel tablemodele;
}
