/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.GUI.gestionTrajet;

import com.example.dao.TrajetUtil;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author yassi
 */
public class ModifierTrajetFrame extends javax.swing.JFrame {

    /**
     * Creates new form modifierTrajetFrame
     */
    public ModifierTrajetFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cID = new javax.swing.JTextField();
        infoComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cUpdate = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("ONCF");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Trajet ID:");

        infoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Station de départ", "Station d'arrivée", "Heure de départ", "Heure d'arrivée", "Tarif" }));
        infoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nouvelle valeur :");

        cUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUpdateActionPerformed(evt);
            }
        });

        updateButton.setText("Modifier");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cID, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(infoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cUpdateActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        switch(infoComboBox.getSelectedItem().toString()) {
            case "Station de départ" : {
            try {
                ModifierStDp();
            } catch (SQLException ex) {
                Logger.getLogger(ModifierTrajetFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            }
            case "Station d'arrivée" : {
            try {
                ModifierStDa();
            } catch (SQLException ex) {
                Logger.getLogger(ModifierTrajetFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            }
            case "Heure de départ" : {
            try {
                Modifierhrdp();
            } catch (SQLException ex) {
                Logger.getLogger(ModifierTrajetFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            }
            case "Heure d'arrivée" : {
            try {
                Modifierhrar();
            } catch (SQLException ex) {
                Logger.getLogger(ModifierTrajetFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            }
            case "Tarif" : {
            try {
                ModifierTarif();
            } catch (SQLException ex) {
                Logger.getLogger(ModifierTrajetFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            }
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void infoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierTrajetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierTrajetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierTrajetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierTrajetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifierTrajetFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cID;
    private javax.swing.JTextField cUpdate;
    private javax.swing.JComboBox<String> infoComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
    private void ModifierStDp() throws SQLException {
        TrajetUtil tu = new TrajetUtil();
        tu.modifierStDepart(Integer.parseInt(cID.getText()),cUpdate.getText());
        JOptionPane.showMessageDialog(null, "station de départ modifié avec succès!", "Succès", JOptionPane.INFORMATION_MESSAGE);
    }
    private void ModifierStDa() throws SQLException {
        TrajetUtil tu = new TrajetUtil();
        tu.modifierStArrivee(Integer.parseInt(cID.getText()),cUpdate.getText());
        JOptionPane.showMessageDialog(null, "station d'arrivée modifié avec succès!", "Succès", JOptionPane.INFORMATION_MESSAGE);
    }
    private void Modifierhrdp() throws SQLException {
        TrajetUtil tu = new TrajetUtil();
        tu.modifierHeureDepart(Integer.parseInt(cID.getText()),cUpdate.getText());
        System.out.println("az");
        JOptionPane.showMessageDialog(null, "Heure de départ modifié avec succès!", "Succès", JOptionPane.INFORMATION_MESSAGE);
    }
    private void Modifierhrar() throws SQLException {
        TrajetUtil tu = new TrajetUtil();
        tu.modifierHeureArrivee(Integer.parseInt(cID.getText()),cUpdate.getText());
        JOptionPane.showMessageDialog(null, "Heure d'arrivée modifié avec succès!", "Succès", JOptionPane.INFORMATION_MESSAGE);
    }
    private void ModifierTarif() throws SQLException {
        TrajetUtil tu = new TrajetUtil();
        tu.modifierTarif(Integer.parseInt(cID.getText()),cUpdate.getText());
        JOptionPane.showMessageDialog(null, "Tarif modifié avec succès!", "Succès", JOptionPane.INFORMATION_MESSAGE);
    }
}
